bundle/Form/MetasCollectionType.php
<?php declare(strict_types=1);

namespace Codein\IbexaSeoToolkit\Form;

use Doctrine\DBAL\Types\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class MetasCollectionType.
 */
final class MetasCollectionType extends AbstractType
{
    public function configureOptions(OptionsResolver $optionsResolver): void
    {
        $optionsResolver->setDefaults(
            [
                'allow_add' => false,
                'allow_delete' => false,
                'entry_type' => TextType::class,
                'entry_options' => [
                    'required' => false,
                ],
                'required' => false,
                'label' => 'field_definition.codeinseometas.fields',
                'translation_domain' => 'fieldtypes',
            ]
        );
    }

    public function getParent(): string
    {
        return CollectionType::class;
    }

    public function getBlockPrefix(): string
    {
        return 'codeinseo_field_type_metas_metas';
    }
}

bundle/templates/content/edit.html.twig
{% extends '@EzPlatformAdminUi/themes/admin/content/form_fields.html.twig' %}

{% block form_row_subfield %}
    {% set is_meta_subfield = (form.parent.vars.name is defined) and (form.parent.vars.name == "metas") %}

    {% if is_meta_subfield %}
        {% set field_type_metas = codein_ibexaseo.field_type_metas %}
        {% set fieldtype_identifier = field_type_metas[name].type %}
        {% set fieldtype_is_not_translatable = false %}

        {% set widget_wrapper_attr = widget_wrapper_attr|default({})|merge({'class': (widget_wrapper_attr.class|default('') ~ ' ez-field-edit__data')|trim}) %}
        {% set wrapper_class = 'border-0 py-2 ez-field-edit ez-field-edit--' ~ fieldtype_identifier %}

        {% for error in form.parent.parent.parent.vars.errors %}
            {% if error.origin == form.vars.errors.form %}
                {% set errors = errors|default([])|merge([error]) %}
            {% endif %}
        {% endfor %}

        {% if required %}{% set wrapper_class = (wrapper_class|default('') ~ ' ez-field-edit--required')|trim %}{% endif %}
        {% if errors|length > 0 %}{% set wrapper_class = (wrapper_class|default('') ~ ' is-invalid')|trim %}{% endif %}
        {% if fieldtype_is_not_translatable %}
            {% set wrapper_class = (wrapper_class|default('') ~ ' ez-field-edit--nontranslatable')|trim %}
            {% set attr = attr|merge({'readonly': 'readonly'}) %}
        {% endif %}

        {% set label_wrapper_attr = label_wrapper_attr|default({})|merge({'class': (label_wrapper_attr.class|default('') ~ 'ez-field-edit__label-wrapper')|trim}) %}
        {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' ez-field-edit__label')|trim}) %}
        {% set attr = attr|merge({'class': (attr.class|default('') ~ ' ez-data-source__input')|trim}) %}
        {% set wrapper_attr = wrapper_attr|default({})|merge({'class': (wrapper_attr.class|default('') ~ ' ' ~ wrapper_class)|trim}) %}

        {% set value = form.parent.vars.value[name] %}

        <div {% with { attr: wrapper_attr } %}{{ block('attributes') }}{% endwith %}>
            <div{% with { attr: label_wrapper_attr } %}{{ block('attributes') }}{% endwith %}>
                {% with { 'compound': false } %}{{- block('form_label') }}{% endwith %}
                {{ block('form_errors') }}
            </div>
            {% if widget_container_block is defined %}
                {{ widget_container_block|raw }}
            {% else %}
                <div{% with { attr: widget_wrapper_attr } %}{{ block('attributes') }}{% endwith %}>
                    {% if fieldtype_identifier == 'ezboolean' %}
                        {% set checked = value %}
                        {{ block('ezplatform_fieldtype_ezboolean_widget') }}
                    {% else %}
                        <div class="ez-data-source">
                            {{- form_widget(form, {'attr': attr}) -}}
                        </div>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    {% else %}
        {{ parent() }}
    {% endif %}

{% endblock %}

bundle/templates/content/robots.html.twig
{% if robots_fields %}
    {% set robots_fields_values = '' %}
    {%- for meta_name, meta_content in robots_fields -%}
        {% set robots_field_name = meta_name|replace({'robots_': ''}) %}
        {% set robots_field_value = meta_content ? robots_field_name : 'no' ~ robots_field_name %}
        {% set robots_fields_values = robots_fields_values ~ robots_field_value  ~ ', ' %}
    {% endfor %}
    <meta name="robots" content="{{ robots_fields_values|trim(', ') }}"/>
{% endif %}

bundle/templates/content/view.html.twig
{% extends "@EzPublishCore/content_fields.html.twig" %}

{%- block codeinseometas_field -%}
    {%- set is_the_canonical_found = false -%}
    {%- set is_the_title_found = false -%}

    {%- set field_value_metas = resolve_pattern(field, fieldSettings, content) -%}
    {% set meta_fields = (codein_ibexaseo.default_metas is defined ? codein_ibexaseo.default_metas : [])|merge(field_value_metas) %}
    {% set robots_fields = meta_fields|filter((meta_name, meta_content) => (meta_content starts with "robots_")) %}
    {% set meta_fields = meta_fields|filter((meta_name, meta_content) => (not (meta_content starts with "robots_"))) %}

    {%- for meta_name, meta_content in meta_fields -%}
        {%- if meta_name is same as("title") -%}
            {%- set is_the_title_found = true -%}
        {%- endif -%}
        {% set field_type_metas = codein_ibexaseo.field_type_metas %}
        {% set type = field_type_metas[meta_name] is defined ? field_type_metas[meta_name].type : 'ezstring' %}
        {% include '@CodeinIbexaSeoToolkit/content/meta_field_type/' ~ type ~ '.html.twig'  ignore missing %}
    {% endfor %}

    {%- if contentInfo.mainLocationId is defined and contentInfo.mainLocationId is not empty and is_the_canonical_found is same as(false) -%}
        <link rel="canonical" href="{{ url('ez_urlalias', {'locationId': contentInfo.mainLocationId}) }}" />
    {%- endif -%}
    {%- if is_the_title_found is same as(false) %}
        <title>{{ ez_content_name(contentInfo) }}</title>
    {% endif -%}

    {% include '@CodeinIbexaSeoToolkit/content/robots.html.twig' %}
{% endblock %}